food_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('home', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('booking', views.booking, name='booking'),
    path("menu/", include("menu.urls")),
    path('members/', include("members.urls")),
    path('booking-submit', views.bookingSubmit, name='bookingSubmit'),
    path('user-panel', views.userPanel, name='userPanel'),
    path('user-update/<int:id>', views.userUpdate, name='userUpdate'),
    path('user-update-submit/<int:id>', views.UserUpdateSubmit, name='userUpdateSubmit'),
    path('staff-panel', views.staffPanel, name='staffPanel'),
]

menu/urls.py
from django.urls import path

from menu.views import FoodCategoryListView, FoodCategoryDetailView, FoodCategoryCreateView, FoodCategoryUpdateView


app_name = "menu"

urlpatterns = [
    path(
    "categories/",
    FoodCategoryListView.as_view(),
    name = "categories_list"
    ),

    path(
    "category/<int:pk>/",
    FoodCategoryDetailView.as_view(),
    name = "category_detail"
    ),

    path(
    "create/category",
    FoodCategoryCreateView.as_view(),
    name = "create_category"
    ),

    path(
    "update/<int:pk>/category",
    FoodCategoryUpdateView.as_view(),
    name = "update_category"
    )
]

menu/models.py
from django.db import models

class FoodCategory(models.Model):

    name = models.CharField(max_length=255)
    description = models.TextField()


class Dish(models.Model):

    name = models.CharField(max_length=255)
    description = models.TextField()

    category = models.ForeignKey(FoodCategory, on_delete=models.PROTECT)
    

menu/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse_lazy

from menu.models import FoodCategory


__all__ = [
    "FoodCategoryCreateView",
    "FoodCategoryDetailView",
    "FoodCategoryListView"
]

class FoodCategoryListView(ListView):
    model = FoodCategory


class FoodCategoryDetailView(DetailView):
    model = FoodCategory


class FoodCategoryCreateView(CreateView):
    model = FoodCategory
    fields = ("name", "description")

    success_url = reverse_lazy("menu:categories_list")

class FoodCategoryUpdateView(UpdateView):
     model = FoodCategory
     fields = ("name", "description")

     success_url = reverse_lazy("menu:categories_list")

menu/templates/menu/foodcategory_detail.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Categories {{ object.id }} : {{ object.name }}</h1>
<p><a href="{% url 'menu:categories_list' %}">Torna alla lista di categorie</a></p>
    <p>{{ object.description }}</p>
</body>
</html>

menu/templates/menu/foodcategory_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>Category Form</h1>
    
<form action="" method="post">
    {{ form.as_p }}
    <input type="submit" value="Salva">
</form>

<p>
    <a href="{% url 'menu:create_category' %}">Crea nuovo oggetto</a>
</p>


</body>
</html>

menu/templates/menu/foodcategory_list.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Categories List</h1>

    {% for el in object_list %}
     <p>
            {{ el.id }} : {{ el.nome }}
        <a href="{% url 'menu:category_detail' el.id %}">Visualizza Dettaglio</a>
     </p>
    {% endfor %}
    <p>
        <a href="{% url 'menu:create_category' %}">Crea nuovo oggetto</a>
    </p>
    
</body>
</html>